#!/usr/bin/env python3
"""Generates the iOS PWA launch images (apple-touch-startup-image).

An installed web app on iOS shows a blank screen while it boots unless the
layout declares a startup image matching that exact device. Re-run this after a
brand asset change:

    python3 script/generate_pwa_splash.py

Writes public/splash/*.png plus app/views/layouts/_pwa_splash.html.erb, so the
device table below stays the single source of truth for both.
"""

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / 'public' / 'favicon-512x512.png'
OUT_DIR = ROOT / 'public' / 'splash'
PARTIAL = ROOT / 'app' / 'views' / 'layouts' / '_pwa_splash.html.erb'

# Backgrounds mirror --background-color in dashboard/assets/scss/_next-colors.scss.
# The mark sits on a white tile in both themes: its darkest stroke (#003c55)
# would otherwise vanish against the dark background.
THEMES = {
    'light': (247, 247, 247),
    'dark': (28, 29, 32),
}

TILE_RATIO = 0.26  # tile side, relative to the short edge
CORNER_RATIO = 0.225  # corner radius, relative to the tile side
LOGO_RATIO = 0.72  # mark size, relative to the tile side

# device-width, device-height (CSS px), device pixel ratio. Portrait only, since
# the manifest locks the app to portrait.
DEVICES = [
    (375, 667, 2, 'iPhone SE, 8'),
    (414, 736, 3, 'iPhone 8 Plus'),
    (375, 812, 3, 'iPhone X, XS, 11 Pro, 12/13 mini'),
    (414, 896, 2, 'iPhone XR, 11'),
    (414, 896, 3, 'iPhone XS Max, 11 Pro Max'),
    (390, 844, 3, 'iPhone 12, 13, 14, 16e'),
    (428, 926, 3, 'iPhone 12/13 Pro Max, 14 Plus'),
    (393, 852, 3, 'iPhone 14 Pro, 15, 15 Pro, 16'),
    (430, 932, 3, 'iPhone 14 Pro Max, 15 Plus, 15 Pro Max, 16 Plus'),
    (402, 874, 3, 'iPhone 16 Pro'),
    (440, 956, 3, 'iPhone 16 Pro Max'),
]


def build_image(width, height, background):
    canvas = Image.new('RGB', (width, height), background)

    tile = int(min(width, height) * TILE_RATIO)
    # PIL does not antialias shapes, so the tile is drawn oversized and reduced.
    scale = 4
    layer = Image.new('RGBA', (tile * scale, tile * scale), (0, 0, 0, 0))
    ImageDraw.Draw(layer).rounded_rectangle(
        [0, 0, tile * scale - 1, tile * scale - 1],
        radius=int(tile * CORNER_RATIO) * scale,
        fill=(255, 255, 255, 255),
    )
    layer = layer.resize((tile, tile), Image.LANCZOS)

    logo_side = int(tile * LOGO_RATIO)
    logo = Image.open(LOGO).convert('RGBA').resize(
        (logo_side, logo_side), Image.LANCZOS
    )
    offset = (tile - logo_side) // 2
    layer.paste(logo, (offset, offset), logo)

    canvas.paste(layer, ((width - tile) // 2, (height - tile) // 2), layer)
    return canvas


def media_query(css_width, css_height, ratio, theme):
    return (
        f'screen and (device-width: {css_width}px) '
        f'and (device-height: {css_height}px) '
        f'and (-webkit-device-pixel-ratio: {ratio}) '
        f'and (orientation: portrait) '
        f'and (prefers-color-scheme: {theme})'
    )


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        '<%# Generated by script/generate_pwa_splash.py — do not edit by hand. %>'
    ]

    for css_width, css_height, ratio, label in DEVICES:
        width, height = css_width * ratio, css_height * ratio
        lines.append(f'<%# {label} %>')
        for theme, background in THEMES.items():
            name = f'apple-splash-{theme}-{width}-{height}.png'
            build_image(width, height, background).save(
                OUT_DIR / name, optimize=True
            )
            lines.append(
                '<link rel="apple-touch-startup-image" '
                f'media="{media_query(css_width, css_height, ratio, theme)}" '
                f'href="/splash/{name}">'
            )

    PARTIAL.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{len(DEVICES) * len(THEMES)} images -> {OUT_DIR}')
    print(f'partial -> {PARTIAL}')


if __name__ == '__main__':
    main()
