class Whatsapp::Providers::WhatsappCloudService < Whatsapp::Providers::BaseService
  WHATSAPP_API_VERSION = 'v22.0'.freeze

  def send_message(phone_number, message)
    @message = message
    send_reaction_if_present(phone_number, message)

    if message.attachments.present? && sticker_message?(message)
      send_sticker_message(phone_number, message)
    elsif message.attachments.present?
      send_attachment_message(phone_number, message)
    elsif message.content_attributes&.dig('rich_media').present?
      send_rich_media_message(phone_number, message, message.content_attributes['rich_media'])
    elsif message.content_type == 'input_select'
      send_interactive_text_message(phone_number, message)
    elsif message.content_type == 'integrations' && message.content_attributes&.dig('interactive').present?
      # SocialWise Async: mensagem interativa enviada via Agent Bot API
      interactive_payload = message.content_attributes['interactive']
      send_interactive_payload(phone_number, message, interactive_payload)
    elsif message.content_type == 'template' && message.content_attributes&.dig('template_payload').present?
      # SocialWise Flow: template oficial WhatsApp enviado via Agent Bot API
      template_payload = message.content_attributes['template_payload']
      send_template_from_payload(phone_number, message, template_payload)
    elsif message.content.present?
      send_text_message(phone_number, message)
    end
  end

  def send_template(phone_number, template_info, message)
    template_body = template_body_parameters(template_info)

    request_body = {
      messaging_product: 'whatsapp',
      recipient_type: 'individual', # Only individual messages supported (not group messages)
      # BSUID -> `recipient`; phone number -> `to` (see recipient_params in the base provider).
      **recipient_params(phone_number),
      type: 'template',
      template: template_body
    }

    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: request_body.to_json
    )

    process_response(response, message)
  end

  # SocialWise Flow: Sends a complete interactive payload directly to WhatsApp API
  # Used for sending buttons, lists, and other interactive messages generated by external bots
  # @param phone_number [String] The recipient phone number
  # @param message [Message] The message object for tracking
  # @param interactive_payload [Hash] The complete interactive payload from SocialWise Flow
  # @return [String, nil] The WhatsApp message ID or nil on failure
  def send_interactive_payload(phone_number, message, interactive_payload)
    Rails.logger.info '[SOCIALWISE-FLOW-WHATSAPP] === send_interactive_payload called ==='
    Rails.logger.info "[SOCIALWISE-FLOW-WHATSAPP] Phone: #{phone_number}"
    Rails.logger.info "[SOCIALWISE-FLOW-WHATSAPP] Interactive payload: #{interactive_payload.to_json}"

    @message = message

    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: {
        messaging_product: 'whatsapp',
        to: phone_number,
        interactive: interactive_payload,
        type: 'interactive'
      }.to_json
    )

    Rails.logger.info "[SOCIALWISE-FLOW-WHATSAPP] WhatsApp API response code: #{response.code}"
    Rails.logger.info "[SOCIALWISE-FLOW-WHATSAPP] WhatsApp API response body: #{response.body}"

    process_response(response, message)
  end

  # SocialWise Flow: Sends a WhatsApp template using the complete payload from SocialWise
  # Used for official templates sent via Agent Bot API (campaigns, flow builder)
  def send_template_from_payload(phone_number, message, template_payload)
    @message = message

    request_body = template_payload.deep_symbolize_keys
    request_body[:to] = phone_number

    Rails.logger.info "[SOCIALWISE-FLOW-WHATSAPP] send_template_from_payload: #{request_body.dig(:template, :name)} → #{phone_number}"

    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: request_body.to_json
    )

    process_response(response, message)
  end

  # Mark message as read and show typing indicator
  # Uses the combined API endpoint for better UX (mark as read + typing in one call)
  # The typing indicator lasts ~25 seconds or until the next message is sent
  # Non-blocking: failures are logged but do not raise
  # @param whatsapp_message_id [String] The WhatsApp message ID (wamid.xxx)
  def mark_read_with_typing(whatsapp_message_id)
    return if whatsapp_message_id.blank?

    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: {
        messaging_product: 'whatsapp',
        status: 'read',
        message_id: whatsapp_message_id,
        typing_indicator: { type: 'text' }
      }.to_json
    )

    if response.success?
      Rails.logger.info "[WhatsappCloudService] Mark read + typing sent for #{whatsapp_message_id}"
    else
      Rails.logger.warn "[WhatsappCloudService] Mark read + typing failed: #{response.code} - #{response.body}"
    end

    response
  rescue StandardError => e
    Rails.logger.warn "[WhatsappCloudService] Mark read + typing error (non-blocking): #{e.message}"
    nil
  end

  def sync_templates
    # ensuring that channels with wrong provider config wouldn't keep trying to sync templates
    whatsapp_channel.mark_message_templates_updated
    return if (templates = fetch_whatsapp_templates).blank?

    # update_columns skips touch, so bump the cache key ourselves; only if templates changed
    whatsapp_channel.account.update_cache_key('inbox') if templates != whatsapp_channel.message_templates
    # rubocop:disable Rails/SkipsModelValidations
    whatsapp_channel.update_columns(message_templates: templates, message_templates_last_updated: Time.current)
    # rubocop:enable Rails/SkipsModelValidations
  end

  def fetch_whatsapp_templates(after: nil)
    options = { headers: { 'Authorization' => "Bearer #{whatsapp_channel.template_access_token}" } }
    options[:query] = { after: after } if after.present?
    response = HTTParty.get("#{business_account_path}/message_templates", options)
    unless response.success?
      Rails.logger.warn "[WHATSAPP] Template sync failed for account #{whatsapp_channel.account_id} " \
                        "inbox #{whatsapp_channel.inbox&.id}: #{response.code} #{error_message(response)}"
      return []
    end

    next_cursor = response.dig('paging', 'cursors', 'after')

    return response['data'] + fetch_whatsapp_templates(after: next_cursor) if next_cursor.present?

    response['data']
  end

  def validate_provider_config?
    config = whatsapp_channel.provider_config
    response = HTTParty.get("#{business_account_path}/message_templates?access_token=#{config['api_key']}")
    return log_transfer_failure('waba_or_token_check', response) unless response.success?
    # The templates check only proves the WABA/token pair, so verify the phone_number_id belongs to this WABA when it changes.
    return true unless whatsapp_channel.provider_config_changed?

    phone_response = HTTParty.get("#{business_account_path}/phone_numbers?fields=id&limit=100&access_token=#{config['api_key']}")
    ids = phone_response.parsed_response.is_a?(Hash) ? Array(phone_response.parsed_response['data']) : []
    return true if phone_response.success? && ids.any? { |number| number['id'] == config['phone_number_id'].to_s }

    log_transfer_failure('phone_number_id_check', phone_response)
  end

  def api_headers
    { 'Authorization' => "Bearer #{whatsapp_channel.provider_config['api_key']}", 'Content-Type' => 'application/json' }
  end

  def create_csat_template(template_config)
    csat_template_service.create_template(template_config)
  end

  def delete_csat_template(template_name = nil)
    template_name ||= CsatTemplateNameService.csat_template_name(whatsapp_channel.inbox.id)
    csat_template_service.delete_template(template_name)
  end

  def get_template_status(template_name)
    csat_template_service.get_template_status(template_name)
  end

  def media_url(media_id)
    "#{api_base_path}/#{whatsapp_api_version}/#{media_id}"
  end

  private

  # Only saves dropping the embedded_signup source marker are transfer attempts; creation/rotation failures are setup errors. Returns false.
  def log_transfer_failure(check, response)
    return false unless whatsapp_channel.embedded_to_manual_transfer_pending?

    error_message = response.parsed_response.is_a?(Hash) ? response.parsed_response.dig('error', 'message') : nil
    Rails.logger.warn("[WHATSAPP_EMBEDDED_TO_MANUAL] failure account_id=#{whatsapp_channel.account_id} channel_id=#{whatsapp_channel.id} " \
                      "check=#{check} http_status=#{response.code} meta_error=#{error_message}")
    false
  end

  def csat_template_service
    @csat_template_service ||= Whatsapp::CsatTemplateService.new(whatsapp_channel)
  end

  def api_base_path
    ENV.fetch('WHATSAPP_CLOUD_BASE_URL', 'https://graph.facebook.com')
  end

  def phone_id_path(version = whatsapp_api_version)
    "#{api_base_path}/#{version}/#{whatsapp_channel.provider_config['phone_number_id']}"
  end

  def business_account_path
    "#{api_base_path}/#{whatsapp_api_version}/#{whatsapp_channel.provider_config['business_account_id']}"
  end

  def whatsapp_api_version
    GlobalConfigService.load('WHATSAPP_API_VERSION', WHATSAPP_API_VERSION)
  end

  # Sends a rich media message: image+caption when image_url is present, otherwise text with preview_url
  # Used for rich_text interactive templates where the checkout URL goes in the body (opens in external browser)
  def send_rich_media_message(phone_number, message, rich_media)
    @message = message
    image_url = rich_media['image_url'].presence

    body = if image_url
             {
               messaging_product: 'whatsapp',
               to: phone_number,
               type: 'image',
               image: {
                 link: image_url,
                 caption: message.content
               }
             }
           else
             {
               messaging_product: 'whatsapp',
               to: phone_number,
               type: 'text',
               text: { body: message.content, preview_url: true }
             }
           end

    response = HTTParty.post("#{phone_id_path}/messages", headers: api_headers, body: body.to_json)
    process_response(response, message)
  end

  def send_text_message(phone_number, message)
    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: {
        messaging_product: 'whatsapp',
        context: whatsapp_reply_context(message),
        **recipient_params(phone_number),
        text: { body: message.outgoing_content },
        type: 'text'
      }.to_json
    )

    process_response(response, message)
  end

  def send_attachment_message(phone_number, message)
    attachment = message.attachments.first
    normalize_opus_content_type(attachment)
    type = %w[image audio video].include?(attachment.file_type) ? attachment.file_type : 'document'
    type_content = build_attachment_content(type, attachment, message)
    response = HTTParty.post(
      "#{phone_id_path('v24.0')}/messages",
      headers: api_headers,
      body: {
        :messaging_product => 'whatsapp',
        :context => whatsapp_reply_context(message),
        **recipient_params(phone_number),
        'type' => type,
        type.to_s => type_content
      }.to_json
    )

    process_response(response, message)
  end

  # WhatsApp rejects stickers sent by link ("Sticker file could not be processed").
  # The webp must be uploaded to /media first and sent by its media id.
  def send_sticker_message(phone_number, message)
    media_id = upload_sticker_media(message)
    return if media_id.blank?

    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: {
        messaging_product: 'whatsapp',
        context: whatsapp_reply_context(message),
        to: phone_number,
        type: 'sticker',
        sticker: { id: media_id }
      }.to_json
    )

    process_response(response, message)
  end

  # WhatsApp accepts webp ONLY as a sticker, never as an image ("WebP image uploads
  # are not currently supported", error 131053). So any webp attachment is routed here.
  def sticker_message?(message)
    return true if message.content_type == 'sticker'

    message.attachments.first&.file&.content_type == 'image/webp'
  end

  def upload_sticker_media(message)
    data = sticker_upload_bytes(message)
    return if data.blank?

    response = post_sticker_media(data)
    return JSON.parse(response.body)['id'] if response.code.to_i == 200

    fail_sticker_upload(message, response)
    nil
  rescue StandardError => e
    Rails.logger.error "[STICKER] media upload failed: #{e.message}"
    nil
  end

  def sticker_upload_bytes(message)
    attachment = message.attachments.first
    return if attachment.blank?

    bytes = attachment.file.blob.open(&:read)
    # Library stickers are already a WhatsApp-compliant webp; raw webp attachments
    # (e.g. a user-dropped .webp) must be converted to 512px / size-capped first.
    return bytes if message.content_type == 'sticker'

    webp, = Stickers::ConverterService.new(bytes: bytes).to_webp
    webp
  rescue Stickers::ConverterService::InvalidSource => e
    Rails.logger.error "[STICKER] convert failed: #{e.message}"
    nil
  end

  def post_sticker_media(data)
    boundary = "----chatwit#{SecureRandom.hex(8)}"
    uri = URI.parse("#{phone_id_path}/media")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme == 'https'
    request = Net::HTTP::Post.new(uri.request_uri)
    request['Authorization'] = "Bearer #{whatsapp_channel.provider_config['api_key']}"
    request['Content-Type'] = "multipart/form-data; boundary=#{boundary}"
    request.body = sticker_media_body(boundary, data)
    http.request(request)
  end

  def sticker_media_body(boundary, data)
    body = +''.b
    body << "--#{boundary}\r\nContent-Disposition: form-data; name=\"messaging_product\"\r\n\r\nwhatsapp\r\n".b
    body << "--#{boundary}\r\nContent-Disposition: form-data; name=\"file\"; filename=\"sticker.webp\"\r\nContent-Type: image/webp\r\n\r\n".b
    body << data.to_s.b
    body << "\r\n--#{boundary}--\r\n".b
    body
  end

  def fail_sticker_upload(message, response)
    Rails.logger.error "[STICKER] media upload error: #{response.body}"
    message.update!(status: :failed, external_error: parse_sticker_error(response.body) || 'Sticker upload failed')
  end

  def parse_sticker_error(body)
    JSON.parse(body).dig('error', 'message')
  rescue JSON::ParserError
    nil
  end

  def error_message(response)
    # https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes/#sample-response
    response.parsed_response.dig('error', 'message') if response.parsed_response.is_a?(Hash)
  end

  def voice_message?(type, attachment)
    type == 'audio' && attachment.meta&.dig('is_voice_message') && attachment.file.content_type == 'audio/ogg'
  end

  # Marcel gem may re-detect OGG/Opus files as audio/opus after ActiveStorage
  # blob attachment, but WhatsApp Cloud API requires audio/ogg content type
  # for voice messages. Normalize so the download URL serves the correct
  # Content-Type header. No-op when the frontend already uploads as audio/ogg.
  def normalize_opus_content_type(attachment)
    return unless attachment.file.attached?

    blob = attachment.file.blob
    return unless blob.content_type == 'audio/opus'

    return if blob.update(content_type: 'audio/ogg')

    Rails.logger.error("Failed to normalize blob #{blob.id} content_type from audio/opus to audio/ogg")
  end

  def build_attachment_content(type, attachment, message)
    type_content = { 'link' => attachment.download_url }
    type_content['caption'] = message.outgoing_content unless %w[audio sticker].include?(type)
    type_content['filename'] = attachment.file.filename if type == 'document'
    type_content['voice'] = true if voice_message?(type, attachment)
    type_content
  end

  def template_body_parameters(template_info)
    template_body = {
      name: template_info[:name],
      language: {
        code: template_info[:lang_code]
      }
    }

    # Enhanced template parameters structure
    # Note: Legacy format support (simple parameter arrays) has been removed
    # in favor of the enhanced component-based structure that supports
    # headers, buttons, and authentication templates.
    #
    # Expected payload format from frontend:
    # {
    #   processed_params: {
    #     body: { '1': 'John', '2': '123 Main St' },
    #     header: {
    #       media_url: 'https://...',
    #       media_type: 'image',
    #       media_name: 'filename.pdf' # Optional, for document templates only
    #     },
    #     buttons: [{ type: 'url', parameter: 'otp123456' }]
    #   }
    # }
    # This gets transformed into WhatsApp API component format:
    # [
    #   { type: 'body', parameters: [...] },
    #   { type: 'header', parameters: [...] },
    #   { type: 'button', sub_type: 'url', parameters: [...] }
    # ]
    template_body[:components] = template_info[:parameters] || []

    template_body
  end

  def whatsapp_reply_context(message)
    reply_to = message.content_attributes[:in_reply_to_external_id]
    return nil if reply_to.blank?

    {
      message_id: reply_to
    }
  end

  def send_interactive_text_message(phone_number, message)
    payload = create_payload_based_on_items(message)

    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: {
        messaging_product: 'whatsapp',
        **recipient_params(phone_number),
        interactive: payload,
        type: 'interactive'
      }.to_json
    )

    process_response(response, message)
  end

  # Support for Async Button Reaction (Emoji)
  # If the message has a reaction_emoji, send it first
  def send_reaction_if_present(phone_number, message)
    return unless message.content_attributes&.dig('reaction_emoji').present? &&
                  message.content_attributes&.dig('reaction_message_id').present?

    send_reaction(phone_number, message.content_attributes['reaction_message_id'], message.content_attributes['reaction_emoji'])
  end

  def send_reaction(phone_number, message_id, emoji)
    response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: {
        messaging_product: 'whatsapp',
        recipient_type: 'individual',
        to: phone_number,
        type: 'reaction',
        reaction: {
          message_id: message_id,
          emoji: emoji
        }
      }.to_json
    )

    if response.success?
      Rails.logger.info "[WhatsappCloudService] Reaction sent successfully: #{emoji} to #{message_id}"
    else
      Rails.logger.error "[WhatsappCloudService] Failed to send reaction: #{response.code} - #{response.body}"
    end

    response
  end
end

Whatsapp::Providers::WhatsappCloudService.prepend_mod_with('Whatsapp::Providers::WhatsappCloudService')
